near_me/urls.py
from django.urls import path
from near_me import views

app_name = "near_me"

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('receive_location/', views.receive_location, name='receive_location'),
]

projects/urls.py
from django.urls import path
from projects import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "projects"

urlpatterns = [
    path('', views.home, name="home"),
    path('sign_up/', views.sign_up,name="signup"),
    path('sign_in/',views.sign_in, name="signin"),
    path('contact/',views.contact, name="contact"),
    path('about/',views.about, name="about"),
    path('download/',views.download, name="download"),
    path('projects/', views.projects, name="projects"),
    path('projects/<int:pk>', views.project_detail, name="project_detail")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rgho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('near_me/', include('near_me.urls'), name='near_me'),
    path('', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", views.dashboard, name="dashboard"),
    path('login/', views.login_view, name="login")
]

near_me/models.py
from django.contrib.gis.db import models

# Create your models here.
class Shops(models.Model):
    name = models.CharField(max_length=100)
    location = models.PointField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)

projects/models.py
from django.db import models

#set blank and null attr with helper function
def nullable_field(field_class, *args, **kwargs):
    kwargs['blank'] = True
    kwargs['null'] = True
    return field_class(*args, **kwargs)


# Create your models here.
class Project(models.Model):
    date = models.DateField()
    title = models.CharField(max_length=250)
    description = models.TextField()
    technology = models.CharField(max_length=100)
    links = nullable_field(models.URLField, max_length=300)
    image = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.pk}. {self.title}"


class AboutEducation(models.Model):
    campus = nullable_field(models.CharField, max_length=100)
    field = nullable_field(models.CharField ,max_length=50)
    location = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    relevant_courses = nullable_field(models.CharField, max_length=800)

    def __str__(self):
        return f"{self.pk}. {self.campus}"


class AboutExperience(models.Model):
    organization = nullable_field(models.CharField, max_length=100)
    job_title = nullable_field(models.CharField, max_length=100)
    location = nullable_field(models.CharField, max_length=100)
    start_date = nullable_field(models.DateField)
    end_date = nullable_field(models.DateField)
    job_description = nullable_field(models.TextField)
    notes = nullable_field(models.CharField, max_length=200)

    def __str__(self):
        return f"{self.pk}. {self.organization}"


class AboutSkills(models.Model):
    skill = nullable_field(models.CharField, max_length=50)
    description = nullable_field(models.TextField)

    def __str__(self):
        return f"{self.pk}. {self.skill}"


class AboutLanguages(models.Model):
    languages = nullable_field(models.CharField, max_length=100)

    def __str__(self):
        return f"{self.pk}. {self.languages} "
    

class AboutInterests(models.Model):
    interests = nullable_field(models.CharField, max_length=100)

    def __str__(self):
        return f"{self.pk}. {self.interests} "

users/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    pass

near_me/views.py
from django.shortcuts import render
from django.http import HttpResponse
from ipware import get_client_ip
from django.views import generic
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance
from near_me.models import Shops
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


"""
latitude = 52
longitude = 13

user_location = Point(longitude, latitude, srid=4326)

class Home(generic.ListView):
    model = Shops
    context_object_name = "shops"
    queryset = Shops.objects.annotate(
        distance=Distance("location", user_location)).order_by("distance")[0:6]
    template_name = "near_me/near_me.html"
"""

@csrf_exempt
def receive_location(request):
    if request.method == "POST":
        data = json.loads(request.body)
        request.session['latitude'] = data.get('latitude', 5)
        request.session['longitude'] = data.get('longitude', 5)

        return JsonResponse({"status": "success", "message": "Location received."})


class Home(generic.ListView):
    model = Shops
    context_object_name = "shops"
    template_name = "near_me/near_me.html"

    def get_queryset(self):
        # Default to some location if not available in the session
        print(self.request.session.items())  # For debugging

        latitude = self.request.session.get('latitude')
        longitude = self.request.session.get('longitude')

        user_location = Point(longitude, latitude, srid=4326)

        return Shops.objects.annotate(
            distance=Distance("location", user_location)
        ).order_by("distance")[0:6]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latitude'] = self.request.session.get('latitude')
        context['longitude'] = self.request.session.get('longitude')
        context['ip'] = get_ip(self.request) 
        return context



def get_ip(request):
    client_ip, is_routable = get_client_ip(request)
    return client_ip
'''
def home(request):
    return render(request, 'near_me/near_me.html',
                  {
                      'ip' : get_ip(request),
                  }
                  )
                  '''

projects/views.py
from django.shortcuts import render
from projects.models import Project as proj
from projects.models import AboutEducation as edu
from projects.models import AboutExperience as exp
from projects.models import AboutSkills as sk
from projects.models import AboutLanguages as lan
from projects.models import AboutInterests as intr

# Create your views here.
def home(request):
    return render(request, 'projects/index.html')

def projects(request):
    projects_obj = proj.objects.all()
    print(projects_obj)
    return render(request, 'projects/projects.html',
                   {'projects' : projects_obj}
                   )

def sign_up(request):
    return render(request, 'projects/sign_up.html')

def sign_in(request):
    return render(request, 'projects/sign_in.html')

def about(request):
    about_edu = edu.objects.all()
    about_exp = exp.objects.all()
    about_proj = proj.objects.all()
    about_skills = sk.objects.all()
    about_languages = lan.objects.all()
    about_interests = intr.objects.all()

    return render(request, 'projects/about.html',
                  {'education' : about_edu,
                   'experience' : about_exp,
                   'projects' : about_proj,
                   'skills' : about_skills,
                   'languages' : about_languages,
                   'interests' : about_interests
                   }
                  )

def contact(request):
    return render(request, 'projects/contact.html')

def download(request):
    return render(request, 'projects/download.html')

def project_detail(request, pk):
    projects = proj.objects.get(pk=pk)
    return render(request, 'projects/project_detail.html', 
                  {'projects' : projects}
                  )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login


# Create your views here.
def dashboard(request):
    return render(request, "dashboard.html")

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('users:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form}) 

near_me/templates/near_me/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'projects/assets/css/style.css' %}">

    <title>{% block title %}  {% endblock %}</title>
    
</head>
<body>

<nav class="navbar bg-dark border-bottom border-body border-success navbar-expand-lg" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">rgho</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                  <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-current="page" href="{% url 'projects:home' %}">Home</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'projects' %}active{% endif %}" href="{% url 'projects:projects' %}">Projects</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'projects:about' %}">About</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'projects:contact' %}">Contact</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'download' %}active{% endif %}" href="{% url 'projects:download' %}">Download</a>

                
                <!-- Buttons for smaller screens -->
                <div class="d-lg-none d-flex mt-3">
                    <a class="btn btn-outline-success" href="{% url 'users:login' %}" type="submit">Sign in</a>
                    <a class="btn btn-primary ms-2 ml-auto" type="submit">Sign up</a>
                </div>
            </div>
            
            <!-- Buttons for large screens -->
            <div class="d-none d-lg-flex ms-auto">
                    <a class="btn btn-outline-success" href="{% url 'users:login' %}" type="submit">Sign in</a>
                    <a class="btn btn-primary ms-2 ml-auto" type="submit">Sign up</a>
            </div>
        </div>
    </div>
</nav>


{% block content %}

{% endblock %}

<footer class="py-3 my-4 footer-style">
    <ul class="nav justify-content-center border-bottom border-success pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">About</a></li>
    </ul>
    <p class="text-center ">© 2023 rgho</p>
  </footer>
  {% block scripts %}

  {% endblock %}
    <script src="{static projects/assets/js/script.js}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

near_me/templates/near_me/near_me.html
{%extends 'near_me/base.html' %}

{% load static %}
{% csrf_token %}

{%block title %} Geo Webapp | rgho {% endblock %}
{% block content %}


<button onclick="getLocation()">Try It</button>

<p id="demo"></p>
<h2>User's IP:</h2>
<p>{{ ip }}</p>

<h2>User's Location:</h2>
<p>Latitude: {{ latitude }}</p>
<p>Longitude: {{ longitude }}</p>

{% if shops %}
<ul>
    {% for shop in shops %}
    <li>
        {{shop.name}} : {{shop.distance}}
    </li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}
{% block scripts %}

<script>
const x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  
    const latitude = position.coords.latitude;
    const longitude = position.coords.longitude;

    x.innerHTML = "Latitude: " + latitude + 
    "<br>Longitude: " + longitude;

    // Send data to the server using fetch
    fetch('{% url "near_me:receive_location" %}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        },
        body: JSON.stringify({
            'latitude': latitude,
            'longitude': longitude
        })
    }).then(response => response.json()).then(data => {
        console.log(data);
    });
}
</script>

{% endblock %}

projects/templates/projects/about.html
{% extends 'projects/base.html' %}
{% load static %}

{% block title %} 
  About | rgho 
{% endblock %}

{% block content %}


    <div class="container my-5">
        <!-- Education Section -->
        <div class="section-header">EDUCATION</div>
        {% for study in education%}
        <h4>{{study.campus}}</h4>
        <p>{{study.location}} - {{study.start_date}} - {{study.end_date}}</p>
        <ul>
            <li>Relevant courses: {{study.relevant_courses}}</li>
        </ul>
        {% endfor %}
        <hr class="project-cards-hr mx-auto">

        <!-- Experience Section -->
        <div class="section-header">EXPERIENCE</div>

        {% for exp in experience%}
        <h4>{{exp.job_title}}</h4>
        <p>{{exp.organization}} - {{exp.start_date}} - {{end_date}}</p>
        <ul>
            <li>{{exp.job_description}}</li>
        </ul>
        {% endfor %}
                <hr class="project-cards-hr mx-auto">

        <!-- Projects Section -->
        <div class="section-header">PROJECTS</div>
        {% for pj in projects %}
        <h4>{{pj.title}} | {{pj.technology}}</h4>
        <p>{{pj.date}}</p>
        <ul>
            <li>{{pj.description}}.</li>
        </ul>
        {% endfor %}
        <hr class="project-cards-hr mx-auto">

        <!-- Technical Skills Section -->
        <div class="section-header">TECHNICAL SKILLS</div>
        
        <ul class="list-unstyled">
          {% for sk in skills %}
            <li>{{sk.skill}}: {{sk.description}}</li>
            <!-- ... -->
            {% endfor %}
        </ul>

        <hr class="project-cards-hr mx-auto">

        <!-- Other Section -->
        <div class="section-header">OTHER</div>
        <br>
        <h4>Languages</h4>
        {% for lan in others%}
        <p>{{lan.languages}}</p>
        {% endfor%}
        <h4>Hobbies & Interests</h4>
        {% for lan in others%}
          <p>{{lan.interests}}</p>
        {% endfor%}
    </div>

{% endblock %}

projects/templates/projects/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'projects/assets/css/style.css' %}">

    <title>{% block title %} Rouhollah Ghobadinezhad {% endblock %}</title>
</head>
<body>

<nav class="navbar bg-dark border-bottom border-body border-success navbar-expand-lg" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">rgho</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                  <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-current="page" href="{% url 'projects:home' %}">Home</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'projects' %}active{% endif %}" href="{% url 'projects:projects' %}">Projects</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'projects:about' %}">About</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'projects:contact' %}">Contact</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'download' %}active{% endif %}" href="{% url 'projects:download' %}">Download</a>

                
                <!-- Buttons for smaller screens -->
                <div class="d-lg-none d-flex mt-3">
                    <a href="{% url 'users:login' %}"  class="btn btn-outline-success" >Sign in</a>
                    <a class="btn btn-primary ms-2 ml-auto" type="submit">Sign up</a>
                </div>
            </div>
            
            <!-- Buttons for large screens -->
            <div class="d-none d-lg-flex ms-auto">
                    <a href="{% url 'users:login' %}"  class="btn btn-outline-success" >Sign in</a>
                    <a class="btn btn-primary ms-2 ml-auto" type="submit">Sign up</a>
            </div>
        </div>
    </div>
</nav>


{% block content %}

{% endblock %}

<footer class="py-3 my-4 footer-style">
    <ul class="nav justify-content-center border-bottom border-success pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">About</a></li>
    </ul>
    <p class="text-center ">© 2023 rgho</p>
  </footer>
    <script src="{static projects/assets/js/script.js}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

projects/templates/projects/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>rgho | Contact</title>
</head>
<body>
    
</body>
</html>

projects/templates/projects/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>rgho | Download</title>
</head>
<body>
    
</body>
</html>

projects/templates/projects/index.html
{% extends 'projects/base.html'%}
{% load static %}



{% block content %}
<!-- Main content area -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h1>Rouhollah <br> Ghobadinezhad</h1>
            <p> <span class="lp-1">Software Developer</span><br><br> Eager to learn, grow, and contribute to the ever-evolving world of technology. Open to opportunities that fuel my passion and expand my horizons. Let's connect and innovate together. </p>
            <a href="https://www.linkedin.com/in/rouhollah-ghobadinezhad-b55b84174" class="btn btn-primary">Connect</a>
        </div>
        <div class="col-md-6">
            <!-- You can add an image here -->
            <img src="static/projects/assets/img/me.jpeg" alt="rgho" class="img-fluid rounded-4">
        </div>
    </div>
</div>
<div class="d-flex justify-content-center align-items-center full-height">
    <div class="container text-center">
        <h1>This is a centered container</h1>
        <p>Any content you place here will be centered.</p>
    </div>
</div>
{% endblock %}

projects/templates/projects/project_detail.html
{%extends 'projects/base.html' %}
{% load static %}

{%block title %} {{projects.title}} | rgho {% endblock %}
{% block content %}
    <h2> this is project <span style="color: blue;">{{ projects.pk}}</span> </h2>
    <img src="{% static projects.image %}" class="card-img-top" style="max-width: 500px;" alt="{{ project.description }}">
    <h5 class="card-title">{{ projects.title}}</h5>
    <p class="card-text">{{ projects.date}} : {{ projects.description }}
         <br> {{ projects.technology}} <br> Link: <a href="{{ projects.links }}">Visit the project code</a></p>
         
{% endblock %}

projects/templates/projects/projects.html
{% extends 'projects/base.html' %}
{% load static %}

{% block title %} 
  Projects | rgho 
{% endblock %}

{% block content %}
<div class="container-xl py-5">
  <div class="row">
    {% for project in projects %}
      <div class="col-12 col-sm-6 col-md-4 mb-4">
        <div class="card h-100">
          <img src="{% static project.image %}" class="card-img-top img-fluid" alt="{{ project.description }}">
          <div class="card-body d-flex flex-column"> <!-- Add flex here -->
            <div class="mb-auto"> <!-- This div pushes content below it to the bottom -->
              <h5 class="card-title">{{ project.title }}</h5>
              <p class="card-text">
                <hr class="project-cards-hr mx-auto">
                <span class="bold">Date: </span>{{ project.date}} <br> 
                {{ project.description }} <br> 
                <span class="bold">Technology:</span> {{ project.technology }}
              </p>
            </div>
            <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-light mt-3">Details</a> <!-- mt-3 (margin-top) is optional, for spacing -->
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

users/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'projects/assets/css/style.css' %}">

    <title>{% block title %} Rouhollah Ghobadinezhad {% endblock %}</title>
</head>
<body>

    <nav class="navbar bg-dark border-bottom border-body border-success navbar-expand-lg" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">rgho</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav me-auto mb-2 mb-lg-0">
                  <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-current="page" href="{% url 'projects:home' %}">Home</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'projects' %}active{% endif %}" href="{% url 'projects:projects' %}">Projects</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'projects:about' %}">About</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'projects:contact' %}">Contact</a>
                  <a class="nav-link {% if request.resolver_match.url_name == 'download' %}active{% endif %}" href="{% url 'projects:download' %}">Download</a>
            </div>
            

            {% block navbar-items %}
            
            {% endblock %}

    </div>
</nav>


{% block content %}

{% endblock %}

<footer class="py-3 my-4 footer-style">
    <ul class="nav justify-content-center border-bottom border-success pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 ">About</a></li>
    </ul>
    <p class="text-center ">© 2023 rgho</p>
  </footer>
    <script src="{static projects/assets/js/script.js}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

users/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}


{% block navbar-items %}
       <div class="dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'projects/assets/img/profile.png' %}" alt="Profile" class="rounded-circle" style="width: 40px; height: 40px; object-fit: cover;">
        </a>

                    <ul class="list-unstyled dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="">Hello, {{ user.username|default:'Guest' }}!</a></li>
                        <li><a class="dropdown-item" href="#">Account</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Logout</a></li>
                    </ul>
                </li>
        </div>
{% endblock %}

{% block content %}

{% endblock %}

users/templates/users/dashboard.html
{% extends 'users/base.html' %}

{% block content %}
Hello, {{ user.username|default:'Guest' }}!
{% endblock %}